@startuml Use case Quản trị
left to right direction
actor "Quản trị" as QT

rectangle "Hệ thống quản trị" {
    QT -down- (Tìm kiếm sản phẩm)
    QT -down- (Đăng nhập)
    QT -down- (Thêm sản phẩm)
    QT -down- (Xem sản phẩm)
    QT -down- (Tạo danh mục sản phẩm)
    QT -down- (Xem danh mục sản phẩm)
    QT -down- (Tạo bộ sưu tập sản phẩm)
    QT -down- (Xem bộ sưu tập sản phẩm)
    QT -down- (Tạo khuyến mãi)
    QT -down- (Xem khuyến mãi)
    QT -down- (Xem đơn hàng)
    QT -down- (Xem sản phẩm nổi bật)
    QT -down- (Hỗ trợ khách hàng)
    (Tìm kiếm sản phẩm) <.-down- (Tìm kiếm sản phẩm theo danh mục) : <<extend>>
    (Tìm kiếm sản phẩm) <.-down- (Tìm kiếm sản phẩm theo giá) : <<extend>>
    (Tìm kiếm sản phẩm) <.-down- (Tìm kiếm sản phẩm theo tên) : <<extend>>
    (Đăng nhập) <.down- (Đăng xuất) : <<extend>>
    (Đăng nhập) <.down- (Đổi mật khẩu) : <<extend>>
    (Xem sản phẩm) <.down- (Sửa thông tin sản phẩm) : <<extend>>
    (Xem sản phẩm) <.down- (Xóa sản phẩm) : <<extend>>
    (Xem danh mục sản phẩm) <.down- (Sửa danh mục sản phẩm) : <<extend>>
    (Xem danh mục sản phẩm) <.down- (Xóa danh mục sản phẩm) : <<extend>>
    (Xem bộ sưu tập sản phẩm) <.down- (Sửa bộ sưu tập sản phẩm) : <<extend>>
    (Xem bộ sưu tập sản phẩm) <.down- (Xóa bộ sưu tập sản phẩm) : <<extend>>
    (Xem khuyến mãi) <.down- (Sửa khuyến mãi) : <<extend>>
    (Xem khuyến mãi) <.down- (Xóa khuyến mãi) : <<extend>>
    (Xem đơn hàng) <.down- (Xác nhận đơn hàng) : <<extend>>
    (Xác nhận đơn hàng) <.down- (Gửi email) : <<include>>
    (Xác nhận đơn hàng) <.down- (Tiếp nhận đơn hàng) : <<extend>>
    (Xác nhận đơn hàng) <.down- (Hủy đơn hàng) : <<extend>>
    (Hỗ trợ khách hàng) <.-down- (Hỗ trợ qua email) : <<extend>>
    (Hỗ trợ khách hàng) <.-down- (Hỗ trợ qua số điện thoại) : <<extend>>
    (Hỗ trợ khách hàng) <.-down- (Hỗ trợ qua mạng xã hội) : <<extend>>
}
@enduml