@startuml Add product sequence
autonumber
actor Admin
boundary AdminPanel as ap
control AdminController as ac
entity Product as p
database ProductDatabase as pr
Admin -> ap++ : openModal()
Admin++
ap -> ac : addProductForm(product: Product)
ac++
ac -> p : create(product: Product)
p++
p -> pr : findProductByProductId(productId: String)
pr++
alt product id is found in database
ac -> p : updateQuantity(quantity: Number)
p -> pr : update(product: Product)
pr --> p : updated Product
p --> ac : updatedProduct
else product id is not found in database
p -> pr : save(product: Product)
pr --> p-- : new Product
p --> ac-- : newProduct
end
ac --> ap-- : showSuccessMessage()
ap --> Admin-- : closeModal()
Admin--
@enduml