@startuml Add voucher sequence
autonumber
actor Admin
boundary AdminPanel as ap
control AdminController as ac
entity productCollection as p
database ProductCollectionDatabase as pr
Admin -> ap++ : openModal()
Admin++
ap -> ac : deleteProductCollection(productCollectionId: String)
ac++
ac -> p : delete(productCollectionId: String)
p++
p -> pr : remove(productCollectionId: String)
pr --> p-- : success
p --> ac-- : success
ac --> ap-- : showSuccessMessage()
ap --> Admin-- : closeModal()
Admin--
@enduml