@startuml Delete product
autonumber
actor Admin
boundary AdminPanel as ap
control AdminController as ac
entity Product as p
database ProductDatabase as pr
Admin -> ap++ : openModal()
Admin++
ap -> ac : deleteProduct(productId: String)
ac++
ac -> p : delete(productId: String)
p++
p -> pr : remove(productId: String)
pr --> p-- : success
p --> ac-- : success
ac --> ap-- : showSuccessMessage()
ap --> Admin-- : closeModal()
Admin--
@enduml