@startuml Delete product category
autonumber
actor Admin
boundary AdminPanel as ap
control AdminController as ac
entity ProductCategory as p
database ProductCategoryDatabase as pr
Admin -> ap++ : openModal()
Admin++
ap -> ac : deleteProductCategory(productCategoryId: String)
ac++
ac -> p : delete(productCategoryId: String)
p++
p -> pr : remove(productCategoryId: String)
pr --> p-- : success
p --> ac-- : success
ac --> ap-- : showSuccessMessage()
ap --> Admin-- : closeModal()
Admin--
@enduml