@startuml Add voucher sequence
autonumber
actor Admin
boundary AdminPanel as ap
control AdminController as ac
entity Voucher as p
database VoucherDatabase as pr
Admin -> ap++ : openModal()
Admin++
ap -> ac : addVoucherForm(voucher: Voucher)
ac++
ac -> p : edit(voucher: Voucher)
p++
p -> pr : save(voucher: Voucher)
pr --> p-- : updated Voucher
p --> ac-- : updatedVoucher
ac --> ap-- : showSuccessMessage()
ap --> Admin-- : closeModal()
Admin--
@enduml