@startuml Edit product category
autonumber
actor Admin
boundary AdminPanel as ap
control AdminController as ac
entity ProductCategory as p
database ProductCategoryDatabase as pr
Admin -> ap++ : openModal()
Admin++
ap -> ac : addProductCategoryForm(productCategory: ProductCategory)
ac++
ac -> p : edit(productCategory: ProductCategory)
p++
p -> pr : save(productCategory: ProductCategory)
pr --> p-- : updated ProductCategory
p --> ac-- : updatedProductCategory
ac --> ap-- : showSuccessMessage()
ap --> Admin-- : closeModal()
Admin--
@enduml