@startuml Order
actor Customer as c
boundary OrderUI as ou
boundary Payment as p
boundary PaymentPortal as pp
control PaymentController as pcn
database Order as o
boundary EmailService as es


c -> ou : fill in order info
c++
ou++
c -> p : choose payment method
p++
alt credit card
p -> pcn : fill in credit card info
pcn++
pcn -> p : confirm
p -> ou : confirm
p--
ou -> c : confirm
c --> ou : confirm
ou -> pp : pay with credit card
pp++
loop
alt success
pp --> ou : success
ou -> o : save order
o++
else fail
pp --> ou : fail
else loop 5 times
break max try exceeded
pp --> ou : fail
pp--
ou --> c : exit
end
end
end
else cod
c -> ou : choose pay
end
ou -> o : save order
ou--
pcn -> es : request to send email
pcn--
o--
es++
es --> c: send email
c--
es--
@enduml