@startuml Add product collection
|Admin|
start
:(1) Click add product collection button;
|System|
:(2) Display add product collection modal;
|Admin|
:(3) Fill in product collection details;
|System|
:(4) Check if product collection details are valid;
if ((5) valid) then (yes)
|Admin|
:(6) Click submit button;
|System|
:(7) Create product collection details;
:(8) Notification "Product collection successfully added";
else (no)
|System|
:(9) Notification "Invalid product collection details";
endif
stop
@enduml