@startuml Add voucher
|Admin|
start
:(1) Click add voucher button;
|System|
:(2) Display add voucher modal;
|Admin|
:(3) Fill in voucher details;
|System|
:(4) Check if voucher details are valid;
if ((5) valid) then (yes)
|Admin|
:(6) Click submit button;
|System|
:(7) Create voucher details;
:(8) Notification "Voucher successfully added";
else (no)
|System|
:(9) Notification "Invalid voucher details";
endif
stop
@enduml