@startuml Add product
|Admin|
start
:(1) Click add product button;
|System|
:(2) Display add product modal;
|Admin|
:(3) Fill in product details;
|System|
:(4) Check if product details are valid;
if ((5) valid) then (yes)
|Admin|
:(6) Click submit button;
|System|
:(7) Create product details;
:(8) Notification "Product successfully added";
else (no)
|System|
:(9) Notification "Invalid product details";
endif
stop
@enduml