@startuml Add product category
|Admin|
start
:(1) Click add product category button;
|System|
:(2) Display add product category modal;
|Admin|
:(3) Fill in product category details;
|System|
:(4) Check if product category details are valid;
if ((5) valid) then (yes)
|Admin|
:(6) Click submit button;
|System|
:(7) Create product category details;
:(8) Notification "Product category successfully added";
else (no)
|System|
:(9) Notification "Invalid product category details";
endif
stop
@enduml