@startuml Confirm order
|Admin|
start
:(1) Select an order to confirm order;
|System|
:(2) Display details of the order;
|Admin|
:(3) Click confirm button;
|System|
:(4) Update order status to "Confirmed";
:(5) Send notification to customer;
:(6) Notification "Confirm order successfully";
|Admin|
:(7) Click "OK" button;
stop
@enduml