@startuml Confirm order
|Admin|
start
:Select an order to confirm order;
|System|
:Display details of the order;
|Admin|
:Click confirm button;
|System|
:Update order status to "Confirmed";
:Send notification to customer;
:Notification "Confirm order successfully";
|Admin|
:Click "OK" button;
stop
@enduml