@startuml Create order
|Customer|
start
:(1) Select a product to view;
|System|
:(2) Display details of the product;
|Customer|
:(3) Click order button;
|System|
:(4) Navigate customer to payment page;
|Customer|
:(5) Enter address;
:(6) Choose payment method;
switch ((7) Payment method)
case (Credit card)
    |Customer|
    :(8) Enter credit card details;
case (COD)
    |Customer|
    :(9) continue;
case (Online banking)
    |Customer|
    :(10) Choose bank;
    |System|
    :(11) Navigate customer to payment gateway;
    |Payment gateway|
    :(12) Check validaty of payment details;
    :(13) Process payment;
    |Customer|
    :(14) Enter TAC;
    |System|
    :(15) Verify TAC;
    :(16) Process payment;
    |Customer|
    :(17) Click OK;
endswitch
|Customer|
:(18) Click confirm button;
|System|
:(19) Navigate customer to order confirmation page;
:(20) Display order details;
|Customer|
:(21) Confirm order;
|System|
:(22) Send order confirmation email;
:(23) Navigate customer to home page;
stop
@enduml