@startuml Create order
|Customer|
start
:Select a product to view;
|System|
:Display details of the product;
|Customer|
:Click order button;
|System|
:Navigate customer to payment page;
|Customer|
:Choose payment method;
if (payment method is cod) then (yes)
|System|
:Display order confirmation page;
|Customer|
:Click confirm order;
|System|
:Send confirmed email to customer;
:Notification "Order successfully";
(no) elseif (payment method is credit card) then (yes)
|System|
:Display credit card form;
|Customer|
:Fill in credit card details;
|System|
:Process the payment and send confirmed email to customer;
:Notification "Order successfully";
(no) elseif (payment method is online payment) then (yes)
:Navigate customer to online payment page;
|Customer|
:Scan QR code to pay;
|Payment System|
:Validate token and payment details;
if (payment is successful) then (yes)
|Payment System|
:Navigate customer to order confirmation page;
|Customer|
:Click confirm order;
|System|
:Send confirmed email to customer;
:Notification "Order successfully";
else (no)
|Payment System|
:Display error message;
endif
|System|
:paypal form;
endif
|Customer| 
if (click confirm order) then (yes)
|System|
:Process the payment and send confirmed email to customer;
:Notification "Order successfully";
else (no)
endif
stop
@enduml