@startuml Create order
|Customer|
start
:Select a product to view;
|System|
:Display details of the product;
|Customer|
:Click order button;
|System|
:Navigate customer to payment page;
|Customer|
:Enter address;
:Choose payment method;
switch (Payment method)
case (Credit card)
    |Customer|
    :Enter credit card details;
case (COD)
    |Customer|
    :continue;
case (Online banking)
    |Customer|
    :Choose bank;
    |System|
    :Navigate customer to payment gateway;
    |Payment gateway|
    :Check validaty of payment details;
    :Process payment;
    |Customer|
    :Enter TAC;
    |System|
    :Verify TAC;
    :Process payment;
    |Customer|
    :Click OK;
endswitch
|Customer|
:Click confirm button;
|System|
:Navigate customer to order confirmation page;
:Display order details;
|Customer|
:Confirm order;
|System|
:Send order confirmation email;
:Navigate customer to home page;
stop
@enduml