@startuml Edit product collection
|Admin|
start
:(1) Click edit product collection button;
|System|
:(2) Display edit product collection modal;
|Admin|
:(3) Update product collection details;
|System|
:(4) Check if product collection details are valid;
if ((5) valid) then (yes)
|Admin|
:(6) Click submit button;
|System|
:(7) Update product collection details;
:(8) Notification "Product collection successfully edited";
else (no)
|System|
:(9) Notification "Invalid product collection details";
endif
stop
@enduml