@startuml Edit product
|Admin|
start
:(1) Click edit product button;
|System|
:(2) Display edit product modal;
|Admin|
:(3) Update product details;
|System|
:(4) Check if product details are valid;
if (valid) then (yes)
|Admin|
:(5) Click submit button;
|System|
:(6) Update product details;
:(7) Notification "Product successfully edited";
else (no)
|System|
:(8) Notification "Invalid product details";
endif
stop
@enduml