@startuml Edit voucher
|Admin|
start
:(1) Click edit voucher button;
|System|
:(2) Display edit voucher modal;
|Admin|
:(3) Update voucher details;
|System|
:(4) Check if voucher details are valid;
if ((5) valid) then (yes)
|Admin|
:(6) Click submit button;
|System|
:(7) Update voucher details;
:(8) Notification "Voucher successfully edited";
else (no)
|System|
:(9) Notification "Invalid voucher details";
endif
stop
@enduml