@startuml Signin
|Admin|
start
repeat 
:(1) Enter sign in details;
:(2) Click on sign in button;
|System|
:(3) Send these information 
to Authentication controller;
backward:(4) Notification "Username or password is incorrect";
repeat while ((5) validate data) is (no) not (yes)
:(6) Notification "Logged in sucessfully";
:(7) Redirect the admin to admin page;
stop
@enduml